import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import {
  User, Box, Database, Cpu, Server, Network,
  Layers, Target, Package, Component, Zap,
  Trash2, Copy, ExternalLink, Check, X, ArrowRight,
  Download, ZoomIn, ZoomOut, Maximize2, Frame
} from 'lucide-react';

// ─── Helpers ────────────────────────────────────────────────
let _idCounter = 0;
const uid = () => `el_${++_idCounter}_${Date.now().toString(36)}`;
const clamp = (v, min, max) => Math.min(max, Math.max(min, v));

const toCamelCase = (str) => {
  if (!str) return '';
  return str
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()))
    .join('');
};

const truncate = (s, n = 40) => (s && s.length > n ? s.slice(0, n) + '…' : s || '');

const CARD_W = 240;
const CARD_H = 90;

// ─── Element Type Definitions ───────────────────────────────
const ELEMENT_TYPES = [
  { type: 'person', label: 'Person', dsl: 'person', icon: User, color: '#08427b' },
  { type: 'softwareSystem', label: 'Software System', dsl: 'softwareSystem', icon: Box, color: '#1168bd' },
  { type: 'container', label: 'Container', dsl: 'container', icon: Database, color: '#438dd5', hasTech: true, validParents: ['softwareSystem'] },
  { type: 'component', label: 'Component', dsl: 'component', icon: Component, color: '#85bbf0', hasTech: true, textDark: true, validParents: ['container'] },
  { type: 'deploymentNode', label: 'Deployment Node', dsl: 'deploymentNode', icon: Server, color: '#f97316', hasTech: true, textDark: true, validParents: ['deploymentNode'] },
  { type: 'infrastructureNode', label: 'Infrastructure Node', dsl: 'infrastructureNode', icon: Network, color: '#a855f7', hasTech: true, textDark: true, validParents: ['deploymentNode'] },
];

const GROUP_DEF = { type: 'group', label: 'Group', icon: Frame, color: '#6b7280', isGroup: true };

const VIEW_TYPES = [
  { type: 'systemLandscape', label: 'System Landscape', icon: Layers },
  { type: 'systemContext', label: 'System Context', icon: Target },
  { type: 'containerView', label: 'Container View', icon: Package },
  { type: 'componentView', label: 'Component View', icon: Cpu },
  { type: 'deploymentView', label: 'Deployment View', icon: Server },
  { type: 'dynamicView', label: 'Dynamic View', icon: Zap },
];

const getTypeDef = (type) => ELEMENT_TYPES.find((t) => t.type === type);

// ─── Orthogonal Arrow Path ──────────────────────────────────
function getOrthogonalPath(srcEl, dstEl, allElements) {
  const sw = srcEl._w || CARD_W;
  const sh = srcEl._h || CARD_H;
  const dw = dstEl._w || CARD_W;
  const dh = dstEl._h || CARD_H;

  const scx = srcEl.x + sw / 2;
  const scy = srcEl.y + sh / 2;
  const dcx = dstEl.x + dw / 2;
  const dcy = dstEl.y + dh / 2;

  const dx = dcx - scx;
  const dy = dcy - scy;

  let sx, sy, ex, ey, mx, my, d;

  if (Math.abs(dx) >= Math.abs(dy)) {
    // Horizontal-dominant: exit right/left
    if (dx >= 0) {
      sx = srcEl.x + sw; sy = scy;
      ex = dstEl.x;      ey = dcy;
    } else {
      sx = srcEl.x;       sy = scy;
      ex = dstEl.x + dw;  ey = dcy;
    }
    mx = (sx + ex) / 2;
    d = `M ${sx} ${sy} L ${mx} ${sy} L ${mx} ${ey} L ${ex} ${ey}`;
    my = (sy + ey) / 2;
  } else {
    // Vertical-dominant: exit bottom/top
    if (dy >= 0) {
      sx = scx; sy = srcEl.y + sh;
      ex = dcx; ey = dstEl.y;
    } else {
      sx = scx; sy = srcEl.y;
      ex = dcx; ey = dstEl.y + dh;
    }
    my = (sy + ey) / 2;
    d = `M ${sx} ${sy} L ${sx} ${my} L ${ex} ${my} L ${ex} ${ey}`;
    mx = (sx + ex) / 2;
  }

  return { sx, sy, ex, ey, mx, my, d };
}

// ─── DSL Generator ──────────────────────────────────────────
function generateDSL(elements, relationships, activeView) {
  const lines = [];
  const ind = (n) => '    '.repeat(n);

  lines.push('workspace "My Workspace" "Generated by C4 Builder" {');
  lines.push(`${ind(1)}model {`);

  // Determine which elements are inside which groups (spatial containment)
  const groups = elements.filter((e) => e.type === 'group');
  const modelElements = elements.filter((e) => e.type !== 'group');

  const elementGroupMap = new Map(); // elementId -> groupId
  for (const el of modelElements) {
    const cx = el.x + CARD_W / 2;
    const cy = el.y + CARD_H / 2;
    for (const g of groups) {
      if (cx >= g.x && cx <= g.x + (g.width || 400) && cy >= g.y && cy <= g.y + (g.height || 300)) {
        elementGroupMap.set(el.id, g.id);
        break;
      }
    }
  }

  // Top-level elements (no parentId)
  const topLevel = modelElements.filter((e) => !e.parentId);
  const childrenOf = (parentId) => modelElements.filter((e) => e.parentId === parentId);

  // Group elements by their group assignment
  const groupedTopLevel = new Map(); // groupId -> elements[]
  const ungroupedTopLevel = [];
  for (const el of topLevel) {
    const gid = elementGroupMap.get(el.id);
    if (gid) {
      if (!groupedTopLevel.has(gid)) groupedTopLevel.set(gid, []);
      groupedTopLevel.get(gid).push(el);
    } else {
      ungroupedTopLevel.push(el);
    }
  }

  // Helper to emit an element + its nested children
  const emitElement = (el, depth) => {
    const def = getTypeDef(el.type);
    if (!def) return;
    const id = toCamelCase(el.name) || `unnamed${el.id.slice(0, 6)}`;
    const children = childrenOf(el.id);

    if (children.length > 0) {
      const parts = [`${id} = ${def.dsl} "${el.name || 'Unnamed'}"`];
      if (el.description) parts.push(`"${el.description}"`);
      lines.push(`${ind(depth)}${parts.join(' ')} {`);
      for (const child of children) {
        emitElement(child, depth + 1);
      }
      lines.push(`${ind(depth)}}`);
    } else {
      const parts = [id, '=', def.dsl, `"${el.name || 'Unnamed'}"`];
      if (el.description) parts.push(`"${el.description}"`);
      else if (def.hasTech && el.technology) parts.push('""');
      if (def.hasTech && el.technology) parts.push(`"${el.technology}"`);
      if (el.tags) parts.push(`"${el.tags}"`);
      lines.push(`${ind(depth)}${parts.join(' ')}`);
    }
  };

  // Emit grouped elements
  for (const [gid, groupEls] of groupedTopLevel) {
    const group = groups.find((g) => g.id === gid);
    lines.push(`${ind(2)}group "${group?.name || 'Unnamed Group'}" {`);
    for (const el of groupEls) {
      emitElement(el, 3);
    }
    lines.push(`${ind(2)}}`);
  }

  // Emit ungrouped elements
  for (const el of ungroupedTopLevel) {
    emitElement(el, 2);
  }

  // Relationships
  for (const rel of relationships) {
    const src = modelElements.find((e) => e.id === rel.sourceId);
    const dst = modelElements.find((e) => e.id === rel.targetId);
    if (!src || !dst) continue;
    const srcId = toCamelCase(src.name) || `unnamed${src.id.slice(0, 6)}`;
    const dstId = toCamelCase(dst.name) || `unnamed${dst.id.slice(0, 6)}`;
    const parts = [`${srcId} -> ${dstId}`];
    if (rel.description) parts.push(`"${rel.description}"`);
    if (rel.technology) parts.push(`"${rel.technology}"`);
    lines.push(`${ind(2)}${parts.join(' ')}`);
  }

  lines.push(`${ind(1)}}`);

  // Views
  lines.push(`${ind(1)}views {`);

  const firstSystem = modelElements.find((e) => e.type === 'softwareSystem');
  const firstContainer = modelElements.find((e) => e.type === 'container');
  const sysId = firstSystem ? (toCamelCase(firstSystem.name) || `unnamed${firstSystem.id.slice(0, 6)}`) : null;
  const contId = firstContainer ? (toCamelCase(firstContainer.name) || `unnamed${firstContainer.id.slice(0, 6)}`) : null;

  switch (activeView) {
    case 'systemLandscape':
      lines.push(`${ind(2)}systemLandscape "landscape" {`);
      lines.push(`${ind(3)}include *`);
      lines.push(`${ind(3)}autoLayout tb`);
      lines.push(`${ind(2)}}`);
      break;
    case 'systemContext':
      if (sysId) {
        lines.push(`${ind(2)}systemContext ${sysId} "context" {`);
        lines.push(`${ind(3)}include *`);
        lines.push(`${ind(3)}autoLayout tb`);
        lines.push(`${ind(2)}}`);
      }
      break;
    case 'containerView':
      if (sysId) {
        lines.push(`${ind(2)}container ${sysId} "containers" {`);
        lines.push(`${ind(3)}include *`);
        lines.push(`${ind(3)}autoLayout tb`);
        lines.push(`${ind(2)}}`);
      }
      break;
    case 'componentView':
      if (contId) {
        lines.push(`${ind(2)}component ${contId} "components" {`);
        lines.push(`${ind(3)}include *`);
        lines.push(`${ind(3)}autoLayout tb`);
        lines.push(`${ind(2)}}`);
      }
      break;
    case 'deploymentView':
      lines.push(`${ind(2)}deployment * "live" "deployment" {`);
      lines.push(`${ind(3)}include *`);
      lines.push(`${ind(3)}autoLayout tb`);
      lines.push(`${ind(2)}}`);
      break;
    case 'dynamicView':
      lines.push(`${ind(2)}dynamic * "dynamic" "Dynamic flow" {`);
      for (const rel of relationships) {
        const src = modelElements.find((e) => e.id === rel.sourceId);
        const dst = modelElements.find((e) => e.id === rel.targetId);
        if (!src || !dst) continue;
        const srcId = toCamelCase(src.name) || `unnamed${src.id.slice(0, 6)}`;
        const dstId = toCamelCase(dst.name) || `unnamed${dst.id.slice(0, 6)}`;
        lines.push(`${ind(3)}${srcId} -> ${dstId} "${rel.description || ''}"`);
      }
      lines.push(`${ind(3)}autoLayout`);
      lines.push(`${ind(2)}}`);
      break;
  }

  // Styles
  lines.push(`${ind(2)}styles {`);
  lines.push(`${ind(3)}element "Person" {`);
  lines.push(`${ind(4)}shape Person`);
  lines.push(`${ind(4)}background #08427b`);
  lines.push(`${ind(4)}color #ffffff`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(3)}element "Software System" {`);
  lines.push(`${ind(4)}background #1168bd`);
  lines.push(`${ind(4)}color #ffffff`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(3)}element "Container" {`);
  lines.push(`${ind(4)}background #438dd5`);
  lines.push(`${ind(4)}color #ffffff`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(3)}element "Component" {`);
  lines.push(`${ind(4)}background #85bbf0`);
  lines.push(`${ind(4)}color #000000`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(3)}element "Deployment Node" {`);
  lines.push(`${ind(4)}background #ffffff`);
  lines.push(`${ind(4)}color #000000`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(3)}element "Infrastructure Node" {`);
  lines.push(`${ind(4)}shape RoundedBox`);
  lines.push(`${ind(4)}background #ffffff`);
  lines.push(`${ind(4)}color #000000`);
  lines.push(`${ind(3)}}`);
  lines.push(`${ind(2)}}`);

  lines.push(`${ind(1)}}`);
  lines.push('}');

  return lines.join('\n');
}

// ─── Validation ─────────────────────────────────────────────
function validate(elements, relationships, activeView) {
  const warnings = [];
  const modelElements = elements.filter((e) => e.type !== 'group');
  const firstSystem = modelElements.find((e) => e.type === 'softwareSystem');
  const firstContainer = modelElements.find((e) => e.type === 'container');

  if (modelElements.length === 0) {
    warnings.push({ level: 'error', msg: 'No elements on canvas' });
  }

  for (const el of modelElements) {
    if (!el.name || el.name.trim() === '') {
      warnings.push({ level: 'warn', msg: `Unnamed ${getTypeDef(el.type)?.label || 'element'}` });
    }
    const hasRel = relationships.some((r) => r.sourceId === el.id || r.targetId === el.id);
    if (!hasRel && modelElements.length > 1) {
      warnings.push({ level: 'warn', msg: `"${el.name || 'Unnamed'}" has no relationships` });
    }
  }

  if ((activeView === 'systemContext' || activeView === 'containerView') && !firstSystem) {
    warnings.push({ level: 'warn', msg: 'View requires a Software System element as scope' });
  }
  if (activeView === 'componentView' && !firstContainer) {
    warnings.push({ level: 'warn', msg: 'Component View requires a Container element as scope' });
  }

  const valid = modelElements.length > 0 && !warnings.some((w) => w.level === 'error');
  return { valid, warnings };
}

// ─── Syntax Highlighting ────────────────────────────────────
function highlightDSL(dsl) {
  const keywordSet = new Set([
    'workspace','model','views','styles','systemLandscape','systemContext',
    'container','component','deployment','dynamic','person','softwareSystem',
    'deploymentNode','infrastructureNode','include','autoLayout','shape',
    'background','color','element','tb','lr','group',
  ]);

  return dsl.split('\n').map((line) => {
    let escaped = line.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const commentIdx = escaped.indexOf('//');
    let code = commentIdx >= 0 ? escaped.slice(0, commentIdx) : escaped;
    const comment = commentIdx >= 0 ? `<span style="color:#6b7280">${escaped.slice(commentIdx)}</span>` : '';

    const tokens = [];
    let i = 0;
    while (i < code.length) {
      if (code[i] === '"') {
        const end = code.indexOf('"', i + 1);
        const strEnd = end >= 0 ? end + 1 : code.length;
        tokens.push(`<span style="color:#22c55e">${code.slice(i, strEnd)}</span>`);
        i = strEnd;
      } else if (code[i] === '-' && code.slice(i, i + 5) === '-&gt;') {
        tokens.push('<span style="color:#ef4444;font-weight:700">-&gt;</span>');
        i += 5;
      } else if (code[i] === '-' && code[i + 1] === '>') {
        tokens.push('<span style="color:#ef4444;font-weight:700">-&gt;</span>');
        i += 2;
      } else if (code[i] === '{' || code[i] === '}') {
        tokens.push(`<span style="color:#d4d4d8">${code[i]}</span>`);
        i++;
      } else if (code[i] === '#') {
        let j = i + 1;
        while (j < code.length && /[0-9a-fA-F]/.test(code[j])) j++;
        tokens.push(`<span style="color:#f59e0b">${code.slice(i, j)}</span>`);
        i = j;
      } else if (code[i] === '*') {
        tokens.push('<span style="color:#d4d4d8">*</span>');
        i++;
      } else if (/[a-zA-Z_]/.test(code[i])) {
        let j = i + 1;
        while (j < code.length && /[a-zA-Z0-9_]/.test(code[j])) j++;
        const word = code.slice(i, j);
        tokens.push(keywordSet.has(word)
          ? `<span style="color:#3b82f6;font-weight:600">${word}</span>`
          : `<span style="color:#f97316">${word}</span>`);
        i = j;
      } else if (code[i] === '=') {
        tokens.push('<span style="color:#d4d4d8">=</span>');
        i++;
      } else {
        tokens.push(code[i]);
        i++;
      }
    }
    return tokens.join('') + comment;
  }).join('\n');
}

// ─── Main Component ─────────────────────────────────────────
export default function C4Builder() {
  // State
  const [elements, setElements] = useState([]);
  const [relationships, setRelationships] = useState([]);
  const [activeView, setActiveView] = useState('systemLandscape');
  const [selectedId, setSelectedId] = useState(null);
  const [selectedRelId, setSelectedRelId] = useState(null);
  const [editingId, setEditingId] = useState(null);
  const [draggingId, setDraggingId] = useState(null);
  const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 });
  const [connectingFrom, setConnectingFrom] = useState(null);
  const [relModal, setRelModal] = useState(null);
  const [copied, setCopied] = useState(false);

  // Zoom & Pan
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isPanning, setIsPanning] = useState(false);
  const [panStart, setPanStart] = useState({ x: 0, y: 0 });
  const spaceRef = useRef(false);

  // Group resize
  const [resizingGroupId, setResizingGroupId] = useState(null);
  const [resizeStart, setResizeStart] = useState(null);

  const canvasRef = useRef(null);

  // Derived
  const dsl = useMemo(() => generateDSL(elements, relationships, activeView), [elements, relationships, activeView]);
  const { valid, warnings } = useMemo(() => validate(elements, relationships, activeView), [elements, relationships, activeView]);
  const selectedElement = elements.find((e) => e.id === selectedId);
  const selectedRel = relationships.find((r) => r.id === selectedRelId);

  // Compute parent boundaries for rendering
  const parentBounds = useMemo(() => {
    const bounds = {};
    const modelEls = elements.filter((e) => e.type !== 'group');
    for (const el of modelEls) {
      const children = modelEls.filter((c) => c.parentId === el.id);
      if (children.length === 0) continue;
      const pad = 20;
      const headerH = 40;
      const minX = Math.min(el.x, ...children.map((c) => c.x)) - pad;
      const maxX = Math.max(el.x + CARD_W, ...children.map((c) => c.x + CARD_W)) + pad;
      const maxY = Math.max(el.y + headerH + CARD_H, ...children.map((c) => c.y + CARD_H)) + pad;
      bounds[el.id] = {
        x: minX,
        y: el.y,
        width: maxX - minX,
        height: maxY - el.y + headerH,
      };
    }
    return bounds;
  }, [elements]);

  // ── Keyboard shortcuts ──
  useEffect(() => {
    const down = (e) => {
      if (e.code === 'Space' && !e.target.closest('input, textarea')) {
        e.preventDefault();
        spaceRef.current = true;
      }
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
      if (e.key === 'Delete' || e.key === 'Backspace') {
        if (selectedId) {
          setElements((prev) => prev.filter((el) => el.id !== selectedId));
          setRelationships((prev) => prev.filter((r) => r.sourceId !== selectedId && r.targetId !== selectedId));
          setSelectedId(null);
          setEditingId(null);
        }
        if (selectedRelId) {
          setRelationships((prev) => prev.filter((r) => r.id !== selectedRelId));
          setSelectedRelId(null);
        }
      }
      if (e.key === 'Escape') {
        setSelectedId(null);
        setSelectedRelId(null);
        setEditingId(null);
        setConnectingFrom(null);
        setRelModal(null);
      }
    };
    const up = (e) => {
      if (e.code === 'Space') spaceRef.current = false;
    };
    window.addEventListener('keydown', down);
    window.addEventListener('keyup', up);
    return () => { window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); };
  }, [selectedId, selectedRelId]);

  // ── Screen-to-canvas coordinate helper ──
  const screenToCanvas = useCallback((clientX, clientY) => {
    const rect = canvasRef.current.getBoundingClientRect();
    return {
      x: (clientX - rect.left - pan.x) / zoom,
      y: (clientY - rect.top - pan.y) / zoom,
    };
  }, [zoom, pan]);

  // ── Toolbox drag start ──
  const onToolboxDragStart = useCallback((e, type) => {
    e.dataTransfer.setData('elementType', type);
    e.dataTransfer.effectAllowed = 'copy';
  }, []);

  // ── Canvas drop ──
  const onCanvasDrop = useCallback((e) => {
    e.preventDefault();
    const type = e.dataTransfer.getData('elementType');
    if (!type) return;
    const { x, y } = screenToCanvas(e.clientX, e.clientY);

    if (type === 'group') {
      setElements((prev) => [
        ...prev,
        { id: uid(), type: 'group', name: `Group ${prev.filter((el) => el.type === 'group').length + 1}`, x: x - 200, y: y - 150, width: 400, height: 300, description: '', technology: '', tags: '', url: '', parentId: null },
      ]);
    } else {
      const def = getTypeDef(type);
      const count = elements.filter((el) => el.type === type).length + 1;
      setElements((prev) => [
        ...prev,
        { id: uid(), type, name: `${def.label} ${count}`, description: '', technology: '', tags: '', url: '', x: x - CARD_W / 2, y: y - CARD_H / 2, parentId: null },
      ]);
    }
  }, [elements, screenToCanvas]);

  const onCanvasDragOver = useCallback((e) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
  }, []);

  // ── Zoom ──
  const onWheel = useCallback((e) => {
    e.preventDefault();
    const rect = canvasRef.current.getBoundingClientRect();
    const mx = e.clientX - rect.left;
    const my = e.clientY - rect.top;
    const step = e.deltaY > 0 ? -0.08 : 0.08;
    setZoom((prev) => {
      const next = clamp(prev + step, 0.2, 3);
      const ratio = next / prev;
      setPan((p) => ({
        x: mx - ratio * (mx - p.x),
        y: my - ratio * (my - p.y),
      }));
      return next;
    });
  }, []);

  const fitToScreen = useCallback(() => {
    if (elements.length === 0) return;
    const rect = canvasRef.current.getBoundingClientRect();
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const el of elements) {
      const w = el.type === 'group' ? (el.width || 400) : CARD_W;
      const h = el.type === 'group' ? (el.height || 300) : CARD_H;
      minX = Math.min(minX, el.x);
      minY = Math.min(minY, el.y);
      maxX = Math.max(maxX, el.x + w);
      maxY = Math.max(maxY, el.y + h);
    }
    const contentW = maxX - minX + 80;
    const contentH = maxY - minY + 80;
    const newZoom = clamp(Math.min(rect.width / contentW, rect.height / contentH), 0.2, 2);
    setPan({
      x: (rect.width - contentW * newZoom) / 2 - minX * newZoom + 40 * newZoom,
      y: (rect.height - contentH * newZoom) / 2 - minY * newZoom + 40 * newZoom,
    });
    setZoom(newZoom);
  }, [elements]);

  // ── Pan ──
  const onCanvasMouseDown = useCallback((e) => {
    if (e.button === 1 || (e.button === 0 && spaceRef.current)) {
      e.preventDefault();
      setIsPanning(true);
      setPanStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
    }
  }, [pan]);

  // ── Element dragging on canvas ──
  const onElementMouseDown = useCallback((e, el) => {
    if (e.target.closest('[data-connector]') || e.target.closest('[data-resize]')) return;
    e.stopPropagation();
    const { x, y } = screenToCanvas(e.clientX, e.clientY);
    setDraggingId(el.id);
    setDragOffset({ x: x - el.x, y: y - el.y });
    setSelectedId(el.id);
    setSelectedRelId(null);
  }, [screenToCanvas]);

  // ── Group resize ──
  const onResizeMouseDown = useCallback((e, groupId) => {
    e.stopPropagation();
    e.preventDefault();
    const group = elements.find((el) => el.id === groupId);
    if (!group) return;
    setResizingGroupId(groupId);
    setResizeStart({ mx: e.clientX, my: e.clientY, w: group.width || 400, h: group.height || 300 });
  }, [elements]);

  // ── Unified mouse move ──
  const onCanvasMouseMove = useCallback((e) => {
    if (isPanning) {
      setPan({ x: e.clientX - panStart.x, y: e.clientY - panStart.y });
      return;
    }
    if (resizingGroupId && resizeStart) {
      const dx = (e.clientX - resizeStart.mx) / zoom;
      const dy = (e.clientY - resizeStart.my) / zoom;
      setElements((prev) => prev.map((el) =>
        el.id === resizingGroupId
          ? { ...el, width: Math.max(200, resizeStart.w + dx), height: Math.max(150, resizeStart.h + dy) }
          : el
      ));
      return;
    }
    if (!draggingId) return;
    const { x, y } = screenToCanvas(e.clientX, e.clientY);
    const newX = Math.max(0, x - dragOffset.x);
    const newY = Math.max(0, y - dragOffset.y);

    setElements((prev) => {
      const el = prev.find((e) => e.id === draggingId);
      if (!el) return prev;
      const deltaX = newX - el.x;
      const deltaY = newY - el.y;
      return prev.map((item) => {
        if (item.id === draggingId) return { ...item, x: newX, y: newY };
        // Move children of a parent being dragged
        if (item.parentId === draggingId) return { ...item, x: item.x + deltaX, y: item.y + deltaY };
        return item;
      });
    });
  }, [isPanning, panStart, resizingGroupId, resizeStart, zoom, draggingId, dragOffset, screenToCanvas]);

  const onCanvasMouseUp = useCallback(() => {
    setDraggingId(null);
    setIsPanning(false);
    setResizingGroupId(null);
    setResizeStart(null);
  }, []);

  // ── Connector / Relationship drawing ──
  const onConnectorClick = useCallback((e, elementId) => {
    e.stopPropagation();
    if (connectingFrom && connectingFrom !== elementId) {
      setRelModal({ sourceId: connectingFrom, targetId: elementId, description: '', technology: '' });
      setConnectingFrom(null);
    } else {
      setConnectingFrom(elementId);
    }
  }, [connectingFrom]);

  const onCanvasClick = useCallback((e) => {
    const target = e.target;
    if (target === canvasRef.current || target.hasAttribute('data-canvas-bg') || target.closest('[data-canvas-bg]') === canvasRef.current) {
      setSelectedId(null);
      setSelectedRelId(null);
      setEditingId(null);
      if (connectingFrom) setConnectingFrom(null);
    }
  }, [connectingFrom]);

  const confirmRelationship = useCallback(() => {
    if (!relModal) return;
    setRelationships((prev) => [
      ...prev,
      { id: uid(), sourceId: relModal.sourceId, targetId: relModal.targetId, description: relModal.description, technology: relModal.technology, tags: '' },
    ]);
    setRelModal(null);
  }, [relModal]);

  // ── Properties update ──
  const updateElement = useCallback((id, updates) => {
    setElements((prev) => prev.map((el) => (el.id === id ? { ...el, ...updates } : el)));
  }, []);

  const updateRelationship = useCallback((id, updates) => {
    setRelationships((prev) => prev.map((r) => (r.id === id ? { ...r, ...updates } : r)));
  }, []);

  // ── Copy DSL ──
  const copyDSL = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(dsl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* fallback */ }
  }, [dsl]);

  // ── Export .dsl file ──
  const exportDSL = useCallback(() => {
    const blob = new Blob([dsl], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'workspace.dsl';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [dsl]);

  // ── Clear canvas ──
  const clearCanvas = useCallback(() => {
    setElements([]);
    setRelationships([]);
    setSelectedId(null);
    setSelectedRelId(null);
    setEditingId(null);
    setConnectingFrom(null);
  }, []);

  // ── Possible parents for a given element type ──
  const getPossibleParents = useCallback((el) => {
    const def = getTypeDef(el.type);
    if (!def?.validParents) return [];
    return elements.filter((p) => def.validParents.includes(p.type) && p.id !== el.id && p.parentId !== el.id);
  }, [elements]);

  // ── Determine which elements are parents with children (for boundary rendering) ──
  const parentsWithChildren = useMemo(() => {
    const set = new Set();
    for (const el of elements) {
      if (el.parentId) set.add(el.parentId);
    }
    return set;
  }, [elements]);

  // ─── Render ───────────────────────────────────────────────
  return (
    <div className="flex h-screen w-screen overflow-hidden bg-gray-950 text-white" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
      {/* ═══ LEFT: TOOLBOX ═══ */}
      <div className="w-52 flex-shrink-0 border-r border-gray-800 bg-gray-900 flex flex-col overflow-y-auto">
        <div className="px-3 py-3 border-b border-gray-800">
          <h1 className="text-sm font-bold tracking-wide text-gray-200 flex items-center gap-1.5">
            <Layers size={16} className="text-blue-400" />
            C4 Builder
          </h1>
        </div>

        {/* Model Elements */}
        <div className="px-2 pt-3 pb-1">
          <p className="text-[10px] font-semibold text-gray-500 uppercase tracking-wider px-1 mb-1.5">Model Elements</p>
          {ELEMENT_TYPES.map((def) => {
            const Icon = def.icon;
            return (
              <div
                key={def.type}
                draggable
                onDragStart={(e) => onToolboxDragStart(e, def.type)}
                className="flex items-center gap-2 px-2 py-1.5 mb-0.5 rounded cursor-grab active:cursor-grabbing hover:bg-gray-800 transition-colors select-none"
              >
                <span className="flex-shrink-0 w-6 h-6 rounded flex items-center justify-center" style={{ backgroundColor: def.color + '22', color: def.color }}>
                  <Icon size={14} />
                </span>
                <span className="text-xs text-gray-300">{def.label}</span>
              </div>
            );
          })}
          {/* Group boundary */}
          <div
            draggable
            onDragStart={(e) => onToolboxDragStart(e, 'group')}
            className="flex items-center gap-2 px-2 py-1.5 mb-0.5 rounded cursor-grab active:cursor-grabbing hover:bg-gray-800 transition-colors select-none"
          >
            <span className="flex-shrink-0 w-6 h-6 rounded flex items-center justify-center" style={{ backgroundColor: '#6b728022', color: '#6b7280' }}>
              <Frame size={14} />
            </span>
            <span className="text-xs text-gray-300">Group</span>
          </div>
        </div>

        {/* View Types */}
        <div className="px-2 pt-3 pb-1">
          <p className="text-[10px] font-semibold text-gray-500 uppercase tracking-wider px-1 mb-1.5">View Types</p>
          {VIEW_TYPES.map((v) => {
            const Icon = v.icon;
            const isActive = activeView === v.type;
            return (
              <button
                key={v.type}
                onClick={() => setActiveView(v.type)}
                className={`w-full flex items-center gap-2 px-2 py-1.5 mb-0.5 rounded text-left transition-colors ${
                  isActive ? 'bg-blue-600/20 text-blue-400' : 'text-gray-400 hover:bg-gray-800 hover:text-gray-300'
                }`}
              >
                <Icon size={14} />
                <span className="text-xs">{v.label}</span>
              </button>
            );
          })}
        </div>

        <div className="mt-auto p-2 border-t border-gray-800">
          <button
            onClick={clearCanvas}
            className="w-full flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs text-red-400 hover:bg-red-950/40 rounded transition-colors"
          >
            <Trash2 size={13} />
            Clear Canvas
          </button>
        </div>
      </div>

      {/* ═══ CENTER: CANVAS ═══ */}
      <div className="flex-1 relative overflow-hidden">
        {/* Top bar */}
        <div className="absolute top-0 left-0 right-0 h-9 bg-gray-900/80 backdrop-blur border-b border-gray-800 flex items-center px-3 z-20 gap-2">
          <span className="text-[11px] text-gray-400 flex-1">
            {VIEW_TYPES.find((v) => v.type === activeView)?.label} &middot; {elements.filter((e) => e.type !== 'group').length} elements &middot; {relationships.length} relationships
          </span>
          {connectingFrom && (
            <span className="text-[11px] text-amber-400 animate-pulse">
              Click another element to complete relationship…
            </span>
          )}
          {/* Zoom controls */}
          <div className="flex items-center gap-1">
            <button onClick={() => setZoom((z) => clamp(z - 0.15, 0.2, 3))} className="p-0.5 text-gray-500 hover:text-gray-300 transition-colors" title="Zoom out"><ZoomOut size={14} /></button>
            <span className="text-[10px] text-gray-500 w-9 text-center">{Math.round(zoom * 100)}%</span>
            <button onClick={() => setZoom((z) => clamp(z + 0.15, 0.2, 3))} className="p-0.5 text-gray-500 hover:text-gray-300 transition-colors" title="Zoom in"><ZoomIn size={14} /></button>
            <button onClick={fitToScreen} className="p-0.5 text-gray-500 hover:text-gray-300 transition-colors" title="Fit to screen"><Maximize2 size={14} /></button>
          </div>
        </div>

        <div
          ref={canvasRef}
          data-canvas-bg="true"
          className="absolute inset-0 top-9"
          style={{
            backgroundImage: 'radial-gradient(circle, #374151 1px, transparent 1px)',
            backgroundSize: `${24 * zoom}px ${24 * zoom}px`,
            backgroundPosition: `${pan.x}px ${pan.y}px`,
            cursor: spaceRef.current || isPanning ? 'grab' : 'default',
          }}
          onDrop={onCanvasDrop}
          onDragOver={onCanvasDragOver}
          onMouseDown={onCanvasMouseDown}
          onMouseMove={onCanvasMouseMove}
          onMouseUp={onCanvasMouseUp}
          onClick={onCanvasClick}
          onWheel={onWheel}
        >
          {/* Transform wrapper for zoom/pan */}
          <div style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, transformOrigin: '0 0', position: 'absolute', top: 0, left: 0 }}>

            {/* SVG layer for relationships */}
            <svg className="absolute pointer-events-none" style={{ zIndex: 5, width: '5000px', height: '5000px', overflow: 'visible' }}>
              <defs>
                <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
                  <polygon points="0 0, 10 3.5, 0 7" fill="#94a3b8" />
                </marker>
                <marker id="arrowhead-selected" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
                  <polygon points="0 0, 10 3.5, 0 7" fill="#3b82f6" />
                </marker>
              </defs>
              {relationships.map((rel) => {
                const src = elements.find((e) => e.id === rel.sourceId);
                const dst = elements.find((e) => e.id === rel.targetId);
                if (!src || !dst) return null;
                // Use parent bounds if element is a parent with children
                const srcBounds = parentBounds[src.id]
                  ? { x: parentBounds[src.id].x, y: parentBounds[src.id].y, _w: parentBounds[src.id].width, _h: parentBounds[src.id].height }
                  : { x: src.x, y: src.y, _w: CARD_W, _h: CARD_H };
                const dstBounds = parentBounds[dst.id]
                  ? { x: parentBounds[dst.id].x, y: parentBounds[dst.id].y, _w: parentBounds[dst.id].width, _h: parentBounds[dst.id].height }
                  : { x: dst.x, y: dst.y, _w: CARD_W, _h: CARD_H };
                const { d, mx, my } = getOrthogonalPath(srcBounds, dstBounds, elements);
                const isSel = selectedRelId === rel.id;
                return (
                  <g key={rel.id}>
                    <path d={d} fill="none" stroke="transparent" strokeWidth="16" className="pointer-events-auto cursor-pointer"
                      onClick={(e) => { e.stopPropagation(); setSelectedRelId(rel.id); setSelectedId(null); }}
                    />
                    <path d={d} fill="none" stroke={isSel ? '#3b82f6' : '#94a3b8'} strokeWidth={isSel ? 2.5 : 1.5}
                      markerEnd={isSel ? 'url(#arrowhead-selected)' : 'url(#arrowhead)'}
                    />
                    {(rel.description || rel.technology) && (
                      <foreignObject x={mx - 80} y={my - 22} width="160" height="24" className="pointer-events-none">
                        <div className="flex items-center justify-center h-full">
                          <span className="text-[11px] px-1.5 py-0.5 rounded bg-gray-900/80 whitespace-nowrap" style={{ color: isSel ? '#60a5fa' : '#9ca3af' }}>
                            {rel.description}{rel.technology ? ` [${rel.technology}]` : ''}
                          </span>
                        </div>
                      </foreignObject>
                    )}
                  </g>
                );
              })}
            </svg>

            {/* Layer 1: Group boundaries */}
            {elements.filter((el) => el.type === 'group').map((group) => {
              const isSel = selectedId === group.id;
              const gw = group.width || 400;
              const gh = group.height || 300;
              return (
                <div
                  key={group.id}
                  className="absolute select-none"
                  style={{ left: group.x, top: group.y, width: gw, height: gh, zIndex: 1 }}
                  onMouseDown={(e) => onElementMouseDown(e, group)}
                  onClick={(e) => e.stopPropagation()}
                  onDoubleClick={(e) => { e.stopPropagation(); setEditingId(group.id); setSelectedId(group.id); }}
                >
                  <div className={`w-full h-full rounded-lg border-2 border-dashed transition-all ${isSel ? 'border-blue-500' : 'border-gray-600'}`}
                    style={{ backgroundColor: '#6b728008' }}>
                    <div className="px-3 py-1.5 flex items-center gap-2">
                      <Frame size={13} className="text-gray-500" />
                      <span className="text-xs font-semibold text-gray-400">{group.name || 'Unnamed Group'}</span>
                    </div>
                  </div>
                  {/* Resize handle */}
                  <div
                    data-resize="true"
                    onMouseDown={(e) => onResizeMouseDown(e, group.id)}
                    className="absolute bottom-0 right-0 w-4 h-4 cursor-nwse-resize flex items-center justify-center"
                  >
                    <svg width="8" height="8" viewBox="0 0 8 8"><path d="M 8 0 L 8 8 L 0 8" fill="none" stroke="#6b7280" strokeWidth="1.5" /></svg>
                  </div>
                  {/* Inline edit popover for group */}
                  {editingId === group.id && (
                    <div className="absolute left-0 top-full mt-2 w-64 bg-gray-800 border border-gray-700 rounded-lg shadow-2xl p-3 z-50" onMouseDown={(e) => e.stopPropagation()}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-xs font-semibold text-gray-400">Edit Group</span>
                        <button onClick={() => setEditingId(null)} className="text-gray-500 hover:text-white"><X size={14} /></button>
                      </div>
                      <label className="block">
                        <span className="text-[10px] text-gray-500 uppercase">Name</span>
                        <input type="text" value={group.name} onChange={(e) => updateElement(group.id, { name: e.target.value })}
                          className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" autoFocus />
                      </label>
                    </div>
                  )}
                </div>
              );
            })}

            {/* Layer 2: Parent boundaries (for nested elements) */}
            {Object.entries(parentBounds).map(([parentId, bounds]) => {
              const parent = elements.find((e) => e.id === parentId);
              if (!parent) return null;
              const def = getTypeDef(parent.type);
              if (!def) return null;
              const isSel = selectedId === parentId;
              return (
                <div
                  key={`boundary-${parentId}`}
                  className="absolute select-none"
                  style={{ left: bounds.x, top: bounds.y, width: bounds.width, height: bounds.height, zIndex: 2 }}
                  onMouseDown={(e) => onElementMouseDown(e, parent)}
                  onClick={(e) => e.stopPropagation()}
                  onDoubleClick={(e) => { e.stopPropagation(); setEditingId(parentId); setSelectedId(parentId); }}
                >
                  <div className={`w-full h-full rounded-lg border-2 border-dashed transition-all ${isSel ? 'ring-2 ring-blue-500 ring-offset-1 ring-offset-gray-950' : ''}`}
                    style={{ borderColor: def.color + '80', backgroundColor: def.color + '0a' }}>
                    <div className="px-3 py-1.5 rounded-t-md flex items-center gap-2" style={{ backgroundColor: def.color }}>
                      {React.createElement(def.icon, { size: 14, className: 'text-white/80' })}
                      <span className="text-xs font-semibold text-white">{parent.name || 'Unnamed'}</span>
                      <span className="text-[10px] text-white/60 ml-1">&laquo;{def.label}&raquo;</span>
                    </div>
                  </div>
                  {/* Connector dot */}
                  <button data-connector="true" onClick={(e) => onConnectorClick(e, parent.id)}
                    className={`absolute -right-3 top-1/2 -translate-y-1/2 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all
                      ${connectingFrom === parent.id ? 'bg-amber-400 border-amber-300 scale-110' : 'bg-gray-700 border-gray-600 opacity-0 hover:opacity-100 hover:bg-blue-500 hover:border-blue-400'}`}
                    title="Draw relationship"
                  >
                    <ArrowRight size={12} className={connectingFrom === parent.id ? 'text-gray-900' : 'text-white'} />
                  </button>
                </div>
              );
            })}

            {/* Layer 3: Element cards (non-group, non-expanded-parent) */}
            {elements.filter((el) => el.type !== 'group' && !parentsWithChildren.has(el.id)).map((el) => {
              const def = getTypeDef(el.type);
              if (!def) return null;
              const Icon = def.icon;
              const isSel = selectedId === el.id;
              const isConn = connectingFrom === el.id;
              const textColor = def.textDark ? 'text-gray-900' : 'text-white';
              return (
                <div
                  key={el.id}
                  className="absolute select-none group"
                  style={{ left: el.x, top: el.y, width: CARD_W, zIndex: isSel ? 10 : 4 }}
                  onMouseDown={(e) => onElementMouseDown(e, el)}
                  onClick={(e) => e.stopPropagation()}
                  onDoubleClick={(e) => { e.stopPropagation(); setEditingId(el.id); setSelectedId(el.id); }}
                >
                  <div
                    className={`rounded-lg p-3 border-2 shadow-lg transition-all cursor-move ${
                      isSel ? 'ring-2 ring-blue-500 ring-offset-1 ring-offset-gray-950' : ''
                    } ${isConn ? 'ring-2 ring-amber-400 ring-offset-1 ring-offset-gray-950' : ''}`}
                    style={{ backgroundColor: def.color, borderColor: isSel ? '#3b82f6' : def.color }}
                  >
                    <div className={`flex items-start gap-2 ${textColor}`}>
                      <Icon size={20} className="mt-0.5 flex-shrink-0 opacity-80" />
                      <div className="flex-1 min-w-0">
                        <div className="font-semibold text-sm leading-tight truncate">{el.name || 'Unnamed'}</div>
                        <div className="text-[10px] opacity-70 mt-0.5">&laquo;{def.label}&raquo;</div>
                        {el.description && <div className="text-[11px] opacity-80 mt-1 line-clamp-2">{truncate(el.description, 50)}</div>}
                        {el.technology && <div className="text-[10px] opacity-60 mt-0.5">[{el.technology}]</div>}
                        {el.parentId && <div className="text-[9px] opacity-50 mt-0.5">child of {elements.find((p) => p.id === el.parentId)?.name || '?'}</div>}
                      </div>
                    </div>
                    {/* Connector dot */}
                    <button data-connector="true" onClick={(e) => onConnectorClick(e, el.id)}
                      className={`absolute -right-3 top-1/2 -translate-y-1/2 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all
                        ${isConn ? 'bg-amber-400 border-amber-300 scale-110' : 'bg-gray-700 border-gray-600 opacity-0 group-hover:opacity-100 hover:bg-blue-500 hover:border-blue-400'}`}
                      title="Draw relationship"
                    >
                      <ArrowRight size={12} className={isConn ? 'text-gray-900' : 'text-white'} />
                    </button>
                  </div>

                  {/* Inline edit popover */}
                  {editingId === el.id && (
                    <div className="absolute left-0 top-full mt-2 w-72 bg-gray-800 border border-gray-700 rounded-lg shadow-2xl p-3 z-50" onMouseDown={(e) => e.stopPropagation()}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-xs font-semibold text-gray-400">Edit {def.label}</span>
                        <button onClick={() => setEditingId(null)} className="text-gray-500 hover:text-white"><X size={14} /></button>
                      </div>
                      <label className="block mb-1.5">
                        <span className="text-[10px] text-gray-500 uppercase">Name *</span>
                        <input type="text" value={el.name} onChange={(e) => updateElement(el.id, { name: e.target.value })}
                          className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" autoFocus />
                      </label>
                      <label className="block mb-1.5">
                        <span className="text-[10px] text-gray-500 uppercase">Description</span>
                        <textarea value={el.description} onChange={(e) => updateElement(el.id, { description: e.target.value })}
                          className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none resize-none" rows={2} />
                      </label>
                      {def.hasTech && (
                        <label className="block mb-1.5">
                          <span className="text-[10px] text-gray-500 uppercase">Technology</span>
                          <input type="text" value={el.technology} onChange={(e) => updateElement(el.id, { technology: e.target.value })}
                            className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
                        </label>
                      )}
                      <label className="block mb-1">
                        <span className="text-[10px] text-gray-500 uppercase">Tags</span>
                        <input type="text" value={el.tags} onChange={(e) => updateElement(el.id, { tags: e.target.value })}
                          className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
                      </label>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Empty state */}
          {elements.length === 0 && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <div className="text-center opacity-40">
                <Layers size={48} className="mx-auto mb-3 text-gray-600" />
                <p className="text-sm text-gray-500">Drag elements from the toolbox to get started</p>
                <p className="text-xs text-gray-600 mt-1">Scroll to zoom &middot; Space+drag to pan</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ═══ RIGHT: DSL + PROPERTIES ═══ */}
      <div className="w-80 flex-shrink-0 border-l border-gray-800 bg-gray-900 flex flex-col overflow-hidden">
        {/* DSL Output */}
        <div className="flex-1 flex flex-col overflow-hidden border-b border-gray-800">
          <div className="flex items-center justify-between px-3 py-2 border-b border-gray-800">
            <span className="text-xs font-semibold text-gray-400">Structurizr DSL</span>
            <div className="flex gap-1">
              <button onClick={copyDSL}
                className="flex items-center gap-1 px-2 py-0.5 text-[10px] bg-gray-800 hover:bg-gray-700 text-gray-300 rounded transition-colors">
                {copied ? <><Check size={11} className="text-green-400" /> Copied</> : <><Copy size={11} /> Copy</>}
              </button>
              <button onClick={exportDSL}
                className="flex items-center gap-1 px-2 py-0.5 text-[10px] bg-gray-800 hover:bg-gray-700 text-gray-300 rounded transition-colors">
                <Download size={11} /> .dsl
              </button>
              <a href="https://structurizr.com/dsl" target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-1 px-2 py-0.5 text-[10px] bg-gray-800 hover:bg-gray-700 text-gray-300 rounded transition-colors">
                <ExternalLink size={11} /> Play
              </a>
            </div>
          </div>
          <div className="flex-1 overflow-auto p-3">
            <pre className="text-[11px] leading-relaxed whitespace-pre-wrap break-words"
              style={{ fontFamily: 'JetBrains Mono, Fira Code, monospace' }}
              dangerouslySetInnerHTML={{ __html: highlightDSL(dsl) }} />
          </div>
        </div>

        {/* Validation */}
        <div className="px-3 py-2 border-b border-gray-800">
          <div className="flex items-center gap-1.5 mb-1">
            <span className="text-[10px] font-semibold text-gray-500 uppercase">Validation</span>
            {valid && warnings.length === 0 && (
              <span className="text-[10px] text-green-400 flex items-center gap-0.5"><Check size={11} /> Valid</span>
            )}
          </div>
          {warnings.length > 0 && (
            <div className="space-y-0.5 max-h-20 overflow-y-auto">
              {warnings.map((w, i) => (
                <div key={i} className={`text-[10px] flex items-start gap-1 ${w.level === 'error' ? 'text-red-400' : 'text-amber-400'}`}>
                  <span className="flex-shrink-0 mt-0.5">{w.level === 'error' ? '!' : '!'}</span>
                  <span>{w.msg}</span>
                </div>
              ))}
            </div>
          )}
          {valid && warnings.length === 0 && elements.filter((e) => e.type !== 'group').length > 0 && (
            <div className="text-[10px] text-green-400">Workspace is valid</div>
          )}
        </div>

        {/* Properties Panel */}
        <div className="h-72 overflow-y-auto">
          <div className="px-3 py-2 border-b border-gray-800">
            <span className="text-[10px] font-semibold text-gray-500 uppercase">Properties</span>
          </div>
          {selectedElement && selectedElement.type !== 'group' ? (
            <div className="px-3 py-2 space-y-2">
              <div className="flex items-center gap-2 mb-2">
                {(() => { const Icon = getTypeDef(selectedElement.type)?.icon || Box; return <Icon size={14} style={{ color: getTypeDef(selectedElement.type)?.color }} />; })()}
                <span className="text-xs font-semibold text-gray-300">{selectedElement.name || 'Unnamed'}</span>
              </div>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Name</span>
                <input type="text" value={selectedElement.name}
                  onChange={(e) => updateElement(selectedElement.id, { name: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Type</span>
                <input type="text" value={getTypeDef(selectedElement.type)?.label || selectedElement.type} readOnly
                  className="w-full bg-gray-800/50 border border-gray-700 rounded px-2 py-1 text-xs text-gray-500 mt-0.5 cursor-not-allowed" />
              </label>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Description</span>
                <textarea value={selectedElement.description}
                  onChange={(e) => updateElement(selectedElement.id, { description: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none resize-none" rows={2} />
              </label>
              {getTypeDef(selectedElement.type)?.hasTech && (
                <label className="block">
                  <span className="text-[10px] text-gray-500 uppercase">Technology</span>
                  <input type="text" value={selectedElement.technology}
                    onChange={(e) => updateElement(selectedElement.id, { technology: e.target.value })}
                    className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
                </label>
              )}
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Tags</span>
                <input type="text" value={selectedElement.tags}
                  onChange={(e) => updateElement(selectedElement.id, { tags: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">URL</span>
                <input type="text" value={selectedElement.url}
                  onChange={(e) => updateElement(selectedElement.id, { url: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              {/* Parent selector (nesting) */}
              {getPossibleParents(selectedElement).length > 0 && (
                <label className="block">
                  <span className="text-[10px] text-gray-500 uppercase">Parent (nesting)</span>
                  <select
                    value={selectedElement.parentId || ''}
                    onChange={(e) => updateElement(selectedElement.id, { parentId: e.target.value || null })}
                    className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none"
                  >
                    <option value="">None</option>
                    {getPossibleParents(selectedElement).map((p) => (
                      <option key={p.id} value={p.id}>{p.name} ({getTypeDef(p.type)?.label})</option>
                    ))}
                  </select>
                </label>
              )}
              <div className="text-[10px] text-gray-600 mt-1">
                ID: {toCamelCase(selectedElement.name) || '(empty)'}
              </div>
            </div>
          ) : selectedElement && selectedElement.type === 'group' ? (
            <div className="px-3 py-2 space-y-2">
              <div className="flex items-center gap-2 mb-2">
                <Frame size={14} className="text-gray-500" />
                <span className="text-xs font-semibold text-gray-300">{selectedElement.name || 'Unnamed Group'}</span>
              </div>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Name</span>
                <input type="text" value={selectedElement.name}
                  onChange={(e) => updateElement(selectedElement.id, { name: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <div className="text-[10px] text-gray-600 mt-1">
                Size: {Math.round(selectedElement.width || 400)} x {Math.round(selectedElement.height || 300)}
              </div>
            </div>
          ) : selectedRel ? (
            <div className="px-3 py-2 space-y-2">
              <div className="text-xs font-semibold text-gray-300 mb-2 flex items-center gap-1">
                <ArrowRight size={14} className="text-blue-400" /> Relationship
              </div>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Description</span>
                <input type="text" value={selectedRel.description}
                  onChange={(e) => updateRelationship(selectedRel.id, { description: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Technology</span>
                <input type="text" value={selectedRel.technology}
                  onChange={(e) => updateRelationship(selectedRel.id, { technology: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <label className="block">
                <span className="text-[10px] text-gray-500 uppercase">Tags</span>
                <input type="text" value={selectedRel.tags}
                  onChange={(e) => updateRelationship(selectedRel.id, { tags: e.target.value })}
                  className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-white mt-0.5 focus:border-blue-500 outline-none" />
              </label>
              <div className="text-[10px] text-gray-600 mt-1">
                {elements.find((e) => e.id === selectedRel.sourceId)?.name || '?'} → {elements.find((e) => e.id === selectedRel.targetId)?.name || '?'}
              </div>
            </div>
          ) : (
            <div className="px-3 py-6 text-center text-gray-600">
              <p className="text-[11px]">Select an element or relationship to edit its properties</p>
            </div>
          )}
        </div>
      </div>

      {/* ═══ RELATIONSHIP MODAL ═══ */}
      {relModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setRelModal(null)}>
          <div className="bg-gray-800 border border-gray-700 rounded-xl shadow-2xl p-4 w-80" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <ArrowRight size={16} className="text-blue-400" />
              New Relationship
            </h3>
            <p className="text-[11px] text-gray-400 mb-3">
              {elements.find((e) => e.id === relModal.sourceId)?.name || '?'} → {elements.find((e) => e.id === relModal.targetId)?.name || '?'}
            </p>
            <label className="block mb-2">
              <span className="text-[10px] text-gray-500 uppercase">Description</span>
              <input type="text" value={relModal.description}
                onChange={(e) => setRelModal((p) => ({ ...p, description: e.target.value }))}
                className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-xs text-white mt-0.5 focus:border-blue-500 outline-none"
                autoFocus placeholder="Uses" />
            </label>
            <label className="block mb-3">
              <span className="text-[10px] text-gray-500 uppercase">Technology (optional)</span>
              <input type="text" value={relModal.technology}
                onChange={(e) => setRelModal((p) => ({ ...p, technology: e.target.value }))}
                className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-xs text-white mt-0.5 focus:border-blue-500 outline-none"
                placeholder="HTTPS" />
            </label>
            <div className="flex justify-end gap-2">
              <button onClick={() => setRelModal(null)} className="px-3 py-1 text-xs text-gray-400 hover:text-white transition-colors">Cancel</button>
              <button onClick={confirmRelationship} className="px-3 py-1 text-xs bg-blue-600 hover:bg-blue-500 text-white rounded transition-colors">Create</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
